apiVersion: v1
kind: Namespace
metadata:
  name: speedtest
  labels:
    name: speedtest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
  namespace: speedtest
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: influxdb
  template:
    metadata:
      labels:
        k8s-app: influxdb
    spec:
      containers:
        - name: influxdb
          image: influxdb:1.8.0
          env:
            - name: INFLUXDB_DB
              value: grafana
            - name: INFLUXDB_USER
              value: grafana
            - name: INFLUXDB_USER_PASSWORD
              value: alsdkff2
          volumeMounts:
            - mountPath: /data
              name: influxdb-storage
      volumes:
        - name: influxdb-storage
          persistentVolumeClaim:
            claimName: influxdb-data
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb
  namespace: speedtest
spec:
  type: LoadBalancer
  ports:
    - port: 8086
      targetPort: 8086
  selector:
    k8s-app: influxdb
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-data
  namespace: speedtest
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: speedtest
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: grafana
  template:
    metadata:
      labels:
        k8s-app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana
          ports:
            - containerPort: 3000
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: grafana-storage
      volumes:
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: grafana-storage
---
apiVersion: v1
kind: Service
metadata:
  labels:
    kubernetes.io/name: grafana
  name: grafana
  namespace: speedtest
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    k8s-app: grafana
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-storage
  namespace: speedtest
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: grafana
  namespace: speedtest
spec:
  rules:
    - host: speedtest.local
      http:
        paths:
          - path: /
            backend:
              serviceName: grafana
              servicePort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: speedtest-agent
  namespace: speedtest
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: speedtest-agent
  template:
    metadata:
      labels:
        k8s-app: speedtest-agent
    spec:
      containers:
        - name: speedtest-agent
          image: chriskinsman/speedtest:5
          env:
            - name: DEBUG
              value: speedtest
            - name: INFLUXDB_HOST
              value: influxdb.speedtest
            - name: INFLUXDB_DB
              value: grafana
            - name: INFLUXDB_USER
              value: grafana
            - name: INFLUXDB_USER_PASSWORD
              value: alsdkff2
