{{ if .Values.grafana.hostname }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pispeedtest.labels" . | nindent 4 }}  
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: grafana
      {{- include "pispeedtest.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        k8s-app: grafana
        {{- include "pispeedtest.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:7.0.0
          ports:
            - containerPort: 3000
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: grafana-storage
      volumes:
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: grafana-storage
---
apiVersion: v1
kind: Service
metadata:
  labels:
    kubernetes.io/name: grafana
    {{- include "pispeedtest.labels" . | nindent 4 }}  
  name: grafana
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    k8s-app: grafana
    {{- include "pispeedtest.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-storage
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pispeedtest.labels" . | nindent 4 }}  
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.pvcStorageClass }}
  resources:
    requests:
      storage: 2Gi
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: grafana
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pispeedtest.labels" . | nindent 4 }}  
spec:
  rules:
    - host: {{ required "You must specify a grafana hostname" .Values.grafana.hostname }}
      http:
        paths:
          - path: {{ .Values.grafana.path }}
            backend:
              serviceName: grafana
              servicePort: 3000
{{ end }}