apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pispeedtest.labels" . | nindent 4 }}  
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: influxdb
      {{- include "pispeedtest.selectorLabels" . | nindent 6 }}      
  template:
    metadata:
      labels:
        k8s-app: influxdb
        {{- include "pispeedtest.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: influxdb
          image: influxdb:1.8.0
          env:
            - name: INFLUXDB_DB
              value: {{ .Values.influxdb.db }}
            - name: INFLUXDB_USER
              value: {{ .Values.influxdb.user }}
            - name: INFLUXDB_USER_PASSWORD
              value: {{ required "You must specify an influxdb password" .Values.influxdb.password }}
          volumeMounts:
            - mountPath: /data
              name: influxdb-storage
      volumes:
        - name: influxdb-storage
          persistentVolumeClaim:
            claimName: influxdb-data
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pispeedtest.labels" . | nindent 4 }}  
spec:
  type: LoadBalancer
  ports:
    - port: 8086
      targetPort: 8086
  selector:
    k8s-app: influxdb
    {{- include "pispeedtest.selectorLabels" . | nindent 4 }}    
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-data
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pispeedtest.labels" . | nindent 4 }}  
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.pvcStorageClass }}
  resources:
    requests:
      storage: 2Gi
