apiVersion: apps/v1
kind: Deployment
metadata:
  name: speedtest-agent
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pispeedtest.labels" . | nindent 4 }}  
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: speedtest-agent
      {{- include "pispeedtest.selectorLabels" . | nindent 6 }}      
  template:
    metadata:
      labels:
        k8s-app: speedtest-agent
        {{- include "pispeedtest.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: speedtest-agent
          image: "chriskinsman/speedtest-agent:{{ .Chart.AppVersion }}"
          env:
{{ if .Values.debug }}          
            - name: DEBUG
              value: speedtest-agent*
{{ end }}
            - name: INFLUXDB_HOST
{{ if .Values.influxdb.host }}
              value: {{ .Values.influxdb.host }}
{{ else }}
              value: "influxdb.{{ .Release.Namespace }}"
{{ end }}
            - name: INFLUXDB_DB
              value: {{ required "You must specify an influxdb database" .Values.influxdb.db }}
            - name: INFLUXDB_USER
              value: {{ required "You must specify and influxdb user" .Values.influxdb.user }}
            - name: INFLUXDB_USER_PASSWORD
              value: {{ required "You must specify an influxdb password" .Values.influxdb.password }}
{{ if .Values.serverList }}            
          volumeMounts:
            - name: config-volume
              mountPath: /etc/speedtest-agent
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Release.Name }}-config
{{ end }}