# Default values for pispeedtest.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


grafana:
  hostname: 
  path: "/"

influxdb:
  host:
  db: "grafana"
  user: "grafana"
  password: ""
  
pvcStorageClass: "local-path"

serverList: 

debug: false